.TH "KADC" "8" "May 26, 2020"
.SH "NAME"
kadc \- data collector for kar
.SH "SYNOPSIS"
/usr/lib/ka/kadc
.SH DESCRIPTION
The kstat activity reporter, kar, extends sar (the system activity
reporter) by saving all kstats regularly, rather then a predefined
subset. This allows a much wider range of statistics to be monitored,
without having to choose which statistics to be monitored in advance.
.LP
The kadc script should be run regularly from the sys user's
crontab. Every 5 minutes is suggested. Less frequently means that data
may not be collected with sufficient granularity, while more frequently
may generate too much data to be stored.
.LP
The saved data may be analysed with the kar(1) utility.
.LP
The data archives are zip files named by date, stored in the
/var/adm/ka directory. The zip archives contain individual files for
each reporting interval, the file being a dump of the entire kstat
hierarchy in JSON format.
.SH SEE ALSO
kar(1), kstat(8), kstat(3KSTAT)
