.TH "KAR" "1" "Apr 6, 2014" "kar 1\&.1"
.SH "NAME"
kar \- kstat activity reporter
.SH "SYNOPSIS"
.LP
kar subcommand [arguments]
.SH DESCRIPTION
.LP
The kar command displays data collected by the kstat activity reporter.
.LP
To see the available subcommands, invoke kar without any arguments.
.SH SEE ALSO
.LP
kadc(1M), kstat(1M), kstat(3KSTAT)
