.TH "KAR" "1" "April 23, 2023"
.SH "NAME"
kar \- kstat activity reporter
.SH "SYNOPSIS"
kar subcommand [arguments]
.SH DESCRIPTION
The kar command displays data collected by the kstat activity reporter.
.LP
To see the available subcommands, invoke kar without any arguments.
.SH SEE ALSO
kadc(8), kstat(8), kstat(3KSTAT)
