#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#
# build kar
#
# Usage:
#
# ./build
#    Builds all the java classes and creates the jar
#
# ./build collector
#    Builds the native collector for this platform
#
# ./build pmd
#    Runs the pmd static code analysis tool, if it's installed
#
# ./build javadoc
#    Generates the javadoc
#
# ./build packages
#    Creates SVR4 packages
#

PATH=/usr/jdk/instances/jdk11/bin:$PATH
export PATH

JKDIR=$(dirname "$0")
LIBDIR=${JKDIR}/lib
JARLIBDIR=${LIBDIR}/java
JKJAR=${JARLIBDIR}/jkstat.jar
KJAR=${JARLIBDIR}/kar.jar
HJAR=${JARLIBDIR}/jheatchart-0.6.jar
BUILDJARS=${JKJAR}:${HJAR}

#
# run
# ./build pmd
# to use this, you must have pmd in your path
#
# new PMD version 7 only has categories, configured in pmd-ruleset.xml
#
PMDRULES="./pmd-ruleset.xml"
PMDCACHE="${HOME}/.pmd/cache.kar"

case $1 in
collector)
	ARCH=$(/usr/bin/uname -p)
	mkdir -p bin/"${ARCH}"
	gcc -m64 -o bin/"${ARCH}"/kar_collector -lkstat src/kar_collector.c
	exit 0
	;;
javadoc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -classpath "$BUILDJARS:." -Xdoclint:all -d javadoc uk.co.petertribble.kar
	exit 0
	;;
clean)
	rm -f $(find uk/co -type f -name '*.class')
	rm -f $(find . -type f -name '*~')
	rm -fr javadoc
	exit 0
	;;
pmd)
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "${PMDRULES}" --use-version java-11 --aux-classpath $(echo lib/java/* | sed 's= =:=g') 2>/dev/null
	pmd check --cache "${PMDCACHE}.html" -d help/*.html  -R category/html/bestpractices.xml 2>/dev/null
	exit 0
	;;
spotbugs)
	#
	# spotbugs works on the class files, so those need to be available
	#
	javac -Xlint -Xlint:-rawtypes -classpath ".:${BUILDJARS}" uk/co/petertribble/kar/*.java
	javac -Xlint -classpath ".:${BUILDJARS}" uk/co/petertribble/kar/graphite/*.java
	spotbugs -auxclasspath $(echo lib/java/* | sed 's= =:=g') uk
	exit 0
	;;
packages)
	sed 's:^JARLIBDIR=.*$:JARLIBDIR=/usr/share/kar:' kar > kar.installed
	./mkproto i386 $2 > prototype.i386
	./mkproto sparc $2 > prototype.sparc
	pkgmk -d /tmp -f prototype.i386 -r $(pwd) TRIBkar
	pkgtrans -s /tmp /tmp/TRIBkar-i386.pkg TRIBkar
	rm -fr /tmp/TRIBkar
	pkgmk -d /tmp -f prototype.sparc -r $(pwd) TRIBkar
	pkgtrans -s /tmp /tmp/TRIBkar-sparc.pkg TRIBkar
	rm -fr /tmp/TRIBkar
	ls -l /tmp/TRIBkar-sparc.pkg /tmp/TRIBkar-i386.pkg
	rm prototype.i386 prototype.sparc
	rm kar.installed
	rm -f depend
	exit 0
	;;
esac

javac -Xlint -Xlint:-rawtypes -classpath ".:${BUILDJARS}" uk/co/petertribble/kar/*.java
javac -Xlint -classpath ".:${BUILDJARS}" uk/co/petertribble/kar/graphite/*.java

jar -cf "${KJAR}" $(find uk/co/petertribble/kar -name '*.class') help/*
